import Head from "next/head.js";
import React from "react";
import Navbar from "./Navbar.jsx";

const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav>
                <Navbar />
            </nav>
            <main>{children}</main>
            <footer>Footer</footer>
        </div>
    );
};

export default Layout;
